In [5]:
import numpy as np
from mlreflect.curve_fitter import example_ascii_file_path
#from mlreflect.curve_fitter import CurveFitter
#from mlreflect.models import DefaultTrainedModel

In [6]:
experiment = np.loadtxt(example_ascii_file_path)

In [7]:
q = experiment[:, 0] # Extract q values
experimental_reflectivity = experiment[:, 1:2].T # Extract intensity values

In [7]:
curve_fitter = CurveFitter(DefaultTrainedModel())

In [8]:
experimental_fit_output = curve_fitter.fit_curve(experimental_reflectivity, q, polish=True, optimize_q=True)
pred_experimental_reflectivity = experimental_fit_output['predicted_reflectivity']
pred_experimental_test_labels = experimental_fit_output['predicted_parameters']

In [9]:
np.array(pred_experimental_test_labels).astype(np.float64).flatten()

array([10.        , 10.9789157 ,  1.        ,  2.5       , 10.35159885,
       20.0701    , 17.7735    ,  1.60404294,  0.        ])

In [10]:
experiment.dtype

dtype('float64')

In [16]:
experimental_reflectivity.shape

(1, 52)

ERROR! Session/line number was not unique in database. History logging moved to new session 97


In [8]:
experimental_reflectivity

array([[0.9574816 , 0.94820342, 0.94534074, 0.95230487, 0.95359337,
        0.94913942, 0.93683657, 0.92039916, 0.60654331, 0.34925741,
        0.16574371, 0.07683227, 0.04995361, 0.03298186, 0.0237555 ,
        0.01736032, 0.01326354, 0.01030187, 0.0082099 , 0.00655951,
        0.00525457, 0.00432509, 0.00361483, 0.00304993, 0.00258166,
        0.00210647, 0.00171091, 0.00152393, 0.00134046, 0.00108694,
        0.00089731, 0.00078318, 0.00068633, 0.0006053 , 0.00053425,
        0.00047185, 0.00042054, 0.00037676, 0.00033902, 0.00030543,
        0.00027253, 0.00024309, 0.00022261, 0.00020262, 0.00017743,
        0.0001577 , 0.00014563, 0.00013372, 0.00012167, 0.00011075,
        0.00010085, 0.00009138]])

In [7]:
np.set_printoptions(suppress=True)

In [12]:
experimental_fit_output.keys()

dict_keys(['predicted_reflectivity', 'predicted_parameters', 'best_q_shift', 'best_scaling'])

In [20]:
np.array(experimental_fit_output["predicted_parameters"])

array([[10.        +0.j    , 10.9789157 +0.j    ,  1.        +0.j    ,
         2.5       +0.j    , 10.35159885+0.j    , 20.0701    +0.4571j,
        17.7735    +0.4048j,  1.60404294+0.j    ,  0.        +0.j    ]])

ERROR! Session/line number was not unique in database. History logging moved to new session 106


In [19]:
list(experimental_fit_output["predicted_parameters"])

['SiOx_thickness',
 'Film_thickness',
 'Si_roughness',
 'SiOx_roughness',
 'Film_roughness',
 'Si_sld',
 'SiOx_sld',
 'Film_sld',
 'Air_sld']

In [21]:
np.real(np.array(experimental_fit_output["predicted_parameters"]))

array([[10.        , 10.9789157 ,  1.        ,  2.5       , 10.35159885,
        20.0701    , 17.7735    ,  1.60404294,  0.        ]])

In [22]:
np.imag(np.array(experimental_fit_output["predicted_parameters"]))

array([[0.    , 0.    , 0.    , 0.    , 0.    , 0.4571, 0.4048, 0.    ,
        0.    ]])

In [23]:
np.vectorize(complex)(np.real(np.array(experimental_fit_output["predicted_parameters"])), np.imag(np.array(experimental_fit_output["predicted_parameters"])))

array([[10.        +0.j    , 10.9789157 +0.j    ,  1.        +0.j    ,
         2.5       +0.j    , 10.35159885+0.j    , 20.0701    +0.4571j,
        17.7735    +0.4048j,  1.60404294+0.j    ,  0.        +0.j    ]])

ERROR! Session/line number was not unique in database. History logging moved to new session 107


In [25]:
np.array(experimental_fit_output["predicted_reflectivity"]).shape

(1, 52)

In [8]:
experimental_reflectivity

array([[9.57481604e-01, 9.48203422e-01, 9.45340741e-01, 9.52304867e-01,
        9.53593373e-01, 9.49139418e-01, 9.36836575e-01, 9.20399156e-01,
        6.06543313e-01, 3.49257408e-01, 1.65743706e-01, 7.68322698e-02,
        4.99536135e-02, 3.29818642e-02, 2.37555026e-02, 1.73603195e-02,
        1.32635357e-02, 1.03018723e-02, 8.20990284e-03, 6.55951258e-03,
        5.25456777e-03, 4.32508758e-03, 3.61483422e-03, 3.04992978e-03,
        2.58165638e-03, 2.10647132e-03, 1.71090748e-03, 1.52393489e-03,
        1.34045654e-03, 1.08693727e-03, 8.97310186e-04, 7.83181382e-04,
        6.86333749e-04, 6.05304565e-04, 5.34247485e-04, 4.71846573e-04,
        4.20542182e-04, 3.76761226e-04, 3.39017077e-04, 3.05426712e-04,
        2.72534446e-04, 2.43091632e-04, 2.22614718e-04, 2.02624352e-04,
        1.77429625e-04, 1.57700914e-04, 1.45629724e-04, 1.33717102e-04,
        1.21666464e-04, 1.10749587e-04, 1.00850848e-04, 9.13843274e-05]])